# .github/workflows/build-nginx.yml
name: Build NGINX packages

on:
  push:
    paths:
      - ".meta/**"
  workflow_dispatch:
    inputs:
      flavor:
        description: "stable or mainline"
        type: choice
        required: false
        default: stable
        options: [stable, mainline]
      tag:
        description: "Override pkg-oss tag (e.g., 1.28.1-1). Leave empty to read from file."
        required: false
        default: ""
      targets:
        description: "Space-separated pkg-oss make targets (default: base + all modules)"
        required: false
        default: ""

permissions:
  contents: read

# Avoid overlapping duplicate builds per ref/flavor
concurrency:
  group: build-nginx-${{ github.ref }}-${{ inputs.flavor || 'auto' }}
  cancel-in-progress: false

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      flavor: ${{ steps.out.outputs.flavor }}
    steps:
      - uses: actions/checkout@v4
      - id: out
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            CHANGED=$(git diff --name-only HEAD~1 || true)
            if echo "$CHANGED" | grep -q ".meta/nginx-stable.txt"; then
              F=stable
            elif echo "$CHANGED" | grep -q ".meta/nginx-mainline.txt"; then
              F=mainline
            else
              F=""
            fi
          else
            F=""
          fi
          echo "flavor=$F" >> "$GITHUB_OUTPUT"

  build:
    needs: detect
    # flavor: input > detected > stable
    env:
      FLAVOR: ${{ inputs.flavor || needs.detect.outputs.flavor || 'stable' }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: debian-12
            container_image: debian:12
          - distro: debian-13
            container_image: debian:13

    container:
      image: ${{ matrix.container_image }}

    steps:
      - name: Install build tooling in container
        run: |
          apt-get update -y
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            ca-certificates curl git jq make build-essential devscripts equivs \
            dpkg-dev debhelper quilt lsb-release xsltproc file libxml2-utils
          update-ca-certificates

      - uses: actions/checkout@v4

      - name: Resolve tag and series
        id: ver
        shell: bash
        run: |
          set -euo pipefail
          # tag: input > file
          if [ -n "${{ inputs.tag }}" ]; then
            TAG="${{ inputs.tag }}"
          else
            case "${FLAVOR}" in
              stable)   FILE=".meta/nginx-stable.txt" ;;
              mainline) FILE=".meta/nginx-mainline.txt" ;;
              *) echo "Unknown flavor '${FLAVOR}'"; exit 1 ;;
            esac
            TAG=$(tr -d '\n' < "$FILE" | xargs)
          fi
          [ -n "$TAG" ] || { echo "No tag resolved"; exit 1; }
          NVER="${TAG%-*}"        # 1.28.1
          SERIES="${NVER%.*}"     # 1.28
          echo "tag=$TAG"       >> "$GITHUB_OUTPUT"
          echo "nver=$NVER"     >> "$GITHUB_OUTPUT"
          echo "series=$SERIES" >> "$GITHUB_OUTPUT"
          echo "Resolved $FLAVOR tag: $TAG (series $SERIES)"

      - name: Clone pkg-oss
        run: |
          git clone --branch "${{ steps.ver.outputs.tag }}" --depth=1 https://github.com/nginx/pkg-oss.git
          echo "Using pkg-oss tag: ${{ steps.ver.outputs.tag }}"

      - name: Verify upstream tag exists
        shell: bash
        run: |
          set -euo pipefail
          code=$(curl -sS -o /dev/null -w "%{http_code}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/nginx/pkg-oss/git/ref/tags/${{ steps.ver.outputs.tag }}")
          if [ "$code" != "200" ]; then
            echo "Upstream tag ${{ steps.ver.outputs.tag }} not visible yet (HTTP $code). Try later."
            exit 1
          fi

      - name: Build Debian packages (base + modules like upstream CI)
        working-directory: pkg-oss/debian
        shell: bash
        run: |
          set -euo pipefail
          # Derive default target list like upstream:
          # targets="base module-<each from list-all-modules>"
          if [ -n "${{ inputs.targets }}" ]; then
            targets="${{ inputs.targets }}"
          else
            targets="base"
            while read -r mod rest; do
              targets="$targets module-$mod"
            done < <(make list-all-modules)
          fi

          echo "Targets: $targets"

          # For each target:
          for t in $targets; do
            echo "::group::Prep $t"
            make "rules-$t"
            NGINX_VERSION="${{ steps.ver.outputs.nver }}"
            ctrl="debuild-$t/nginx-${NGINX_VERSION}/debian/control"
            if [ ! -f "$ctrl" ]; then
              echo "Missing control file for $t at $ctrl"; exit 1
            fi
            # Install build-deps like upstream (mk-build-deps)
            mk-build-deps --install --tool="apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes" "$ctrl"
            echo "::endgroup::"

            echo "::group::Build $t"
            make "$t"
            echo "::endgroup::"
          done

          # Collect .deb artifacts
          mkdir -p ../../out
          find debuild-* -name "*.deb" -print -exec cp -v {} ../../out/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nginx-${{ env.FLAVOR }}-${{ steps.ver.outputs.tag }}-${{ matrix.distro }}
          path: out/
          if-no-files-found: error
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FLAVOR: ${{ needs.build.outputs.FLAVOR || env.FLAVOR }}
      TAGVAL:  ${{ needs.build.outputs.tag || steps.resolve.outputs.tag }}
    steps:
      - name: Resolve flavor/tag from prior jobs
        id: resolve
        run: |
          # Prefer env set in the workflow; fall back to parsing the first artifact name
          echo "tag=${{ needs.build.steps.tag.outputs.tag || '' }}" >> "$GITHUB_OUTPUT"
          echo "flavor=${{ env.FLAVOR }}" >> "$GITHUB_OUTPUT"

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          # No name filter so we fetch every distro artifact produced in the matrix
          path: dist

      - name: Gather .deb files
        id: gather
        shell: bash
        run: |
          shopt -s globstar nullglob
          count=$(ls dist/**/*.deb 2>/dev/null | wc -l || true)
          if [ "$count" -eq 0 ]; then
            echo "No .deb artifacts found. Did the build step upload them?"
            exit 1
          fi
          echo "Found $count debs."
          # Produce a checksum file
          (cd dist && find . -type f -name '*.deb' -print0 | xargs -0 sha256sum) > dist/SHA256SUMS
          echo "files=true" >> "$GITHUB_OUTPUT"

      - name: Install gh (already on runner, but verify)
        run: gh --version

      - name: Create or update GitHub Release
        id: release
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          FLAVOR="${{ steps.resolve.outputs.flavor }}"
          TAG="${{ steps.resolve.outputs.tag }}"
          if [ -z "$TAG" ]; then
            echo "No tag resolved from build jobs."
            exit 1
          fi
          RELTAG="nginx-${FLAVOR}-${TAG}"
          TITLE="NGINX ${FLAVOR} ${TAG}"

          # Create release if missing (will fail if exists)
          if ! gh release view "$RELTAG" >/dev/null 2>&1; then
            NOTES=$(cat <<EOF
            Packages for ${TITLE}
            
            - Upstream packaging: nginx/pkg-oss @ ${TAG}
            - Flavor: ${FLAVOR}
            
            Artifacts include .deb packages for all built distros plus SHA256SUMS.
            EOF
            )
            gh release create "$RELTAG" --title "$TITLE" --notes "$NOTES"
          fi

          # Upload all artifacts, clobber on rerun
          gh release upload "$RELTAG" dist/**/*.deb dist/SHA256SUMS --clobber
